### ISSUE TITLE
Store IPFS and contract data separately

### ISSUE THREAD

**Issue by ambertch** [OriginProtocol/demo-dapp#115]
Currently, IPFS and contract data are merged and stored into the listing-detail component state. The data should be stored separately in order to enable features such as showing all fields from the schema that are populated

**Comment by ambertch** [comment]
Linked to #38

**Comment by micahalcorn** [comment]
@wanderingstan isn't the intention here that the DApp developer will eventually make no distinction between contract data and IPFS data?

**Comment by DanielVF** [comment]
@micahalcorn - correct, the DAPP developer will eventually be getting a single, unified set of data about a contract, some of which comes from IPFS, and some of which comes from the contract. 

In the dapp this probably shouldn't be set right onto the top level state of the component, since something could get overwritten this way, but that's a change we can make when switching over the components to use the new stuff in origin.js.
