### ISSUE TITLE
Determine correct gas handling for purchase

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/demo-dapp#16]
It was quick'n'dirty to get purchasing working, with gas for the purchase hard-coded. This needs to be done right. 
~~https://github.com/OriginProtocol/demo-dapp/blob/master/src/services/contract-service.js#L131~~
https://github.com/OriginProtocol/demo-dapp/blob/master/src/services/contract-service.js#L129

**Comment by DanielVF** [comment]
So we do have to send a recommended amount of gas along with the transaction request to the user. Given our gas use tracker, we should be able to pick values that are pretty close to the real costs - and since these gas totals will be in origin.js, our tests will be checking that the estimated amounts actually work.

**Comment by DanielVF** [comment]
This is taken care of for the time being in https://github.com/OriginProtocol/origin-js/pull/118
