### ISSUE TITLE
Complete wrapping of strings with <FormattedMessage> component

### ISSUE THREAD

**Issue by jordajm** [OriginProtocol/demo-dapp#249]
Subtask of: https://github.com/OriginProtocol/demo-dapp/pull/238

A number of JSX files still need to be refactored so that all strings are wrapped in a `<FormattedMessage>` component and given a unique `id` and `defaultMessage`.

**Comment by micahalcorn** [comment]
I have a question about the unique id. It appears that your convention is to use the naming convention `{component-file-name}.{whatever}`. As file names change, that won't cause any problems, will it?

If in one file (say purchase-detail.js) we have a message id `purchase-detail.seller` with a default message of "seller" and then in another file/component we want to translate the string "seller", then would we re-use the message id `purchase-detail.seller` so that we don't have to translate the same string twice with two different message ids?

**Comment by jordajm** [comment]
@micahalcorn - correct, if we change the file name, the ID could either stay the same or change depending on how much we care about naming convention.

Regarding duplicate IDs, at first I tried having a "shared" namespace but `react-intl` threw errors b/c evidently it's not a "best practice" to use the same ID across multiple files. Plus, once there were over a hundred IDs I couldn't keep track of all of what was shared vs unique, so it makes sense to me to keep everything namespaced and unique. 

The exception to that rule is if you have the same string multiple times in the same file, you can re-use the same ID as long as the `defaultMessage` is the same in each case.

**Comment by jordajm** [comment]
Completed by https://github.com/OriginProtocol/demo-dapp/pull/252
