### ISSUE TITLE
Add features from Zeppelin library

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/demo-dapp#25]
Zeppelin docs:
http://zeppelin-solidity.readthedocs.io/en/latest/

We should be using at least `Ownable` and `Migrations`.

**Comment by bretfunk** [comment]
I was able to get both ```Ownable``` and ```Migrations``` working locally but FYI the actual Migration.sol file says: 
```
/**
 * @title Migrations
 * @dev This is a truffle contract, needed for truffle integration, not meant for use by Zeppelin users.
 */
```
You can see it here:
https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/lifecycle/Migrations.sol

However, the file migrates and runs correctly locally and in Remix so I am unsure what they mean by it.  

With my solution users who already have the Dapp locally will need to re-run npm install (to install zeppelin-solidity) and delete all of their json files in the build/contracts directory before running ```migration``` in ```truffle develop``` again otherwise they will receive a ```TypeError: Cannot read property 'call' of undefined``` error when they migrate.

Also, ```Migrations``` inherits from ```Ownable``` so you get both in one inheritance.

I see that there is a branch for this issue, is it recommended that I download and make the changes on that branch before submitting a PR?  Or just submit a PR directly on my own branch?

**Comment by wanderingstan** [comment]
Much like #23 , this involves changes to our contract code, so we need a separate branch for these kind of changes. 

How about something like `topic/contract-dev`?

**Comment by bretfunk** [comment]
We could have an 'interface' contract that calls other contracts.  I haven't tested this but it sounds interesting: https://blog.colony.io/writing-upgradeable-contracts-in-solidity-6743f0eecc88

Just to make sure I am clear, I will create a new branch off of demo-dapp called ```topic/contract-dev``` and will add my solutions to issues #23 and #25.  From there the branch would be merged to master at some future time when we can batch the contract updates together, correct?

**Comment by wanderingstan** [comment]
This is WAY late. Almost have this merged but am hitting a problem with `npm install`. 

Progress is in branch `pr/75` at https://github.com/OriginProtocol/demo-dapp/tree/pr/75

I'll keep working on it tomorrow.

**Comment by bretfunk** [comment]
@wanderingstan did you figure this out?  It's been a bit but the only module I remember adding was Moment.js to make modifying dates easier but I did it the hard way and uninstalled the module in a further push.

Can you tell me the error?

**Comment by wanderingstan** [comment]
@bretfunk Didn't get time today, but am thinking the best path might just be to copy over the relevant bits. 

I hadn't noticed before how much testing coverage you put in there. Nice.
