### ISSUE TITLE
Replace alerts() with styled message boxes

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/demo-dapp#46]
We need a way to show non-modal messages/errors to user.

`overlay.js` can show a message and prevent any user interaction (modal).

But we need a way to show other messages but allow continued user action on the page. For example, when the selected listing upload is too large: https://github.com/OriginProtocol/demo-dapp/blob/master/src/components/listing-create.js#L90
There will surely be more of these. 

Aure will work on a design, though something like the design here would get us started:
https://codeburst.io/displaying-error-messages-in-react-with-a-higher-order-component-hoc-fe2de074bf64

**Comment by ryana** [comment]
I've used this before http://alertifyjs.com -- I really like it. It can replace alerts/confirms (blocking) and it can display disappearing notices (error, warnings, info).

**Comment by joshfraser** [comment]
+1 for Alertify. It's what we're using for notifications on originprotocol.com already, so the consistency would be nice.

**Comment by rvenugopal** [comment]
Please assign to me.  thx

**Comment by wanderingstan** [comment]
Hey @rvenugopal are you still working on this?

**Comment by rvenugopal** [comment]
@wanderingstan Sorry i got sidetracked into learning solidity.  Can you give me a couple more days to work on this?  Sorry for the delay.

**Comment by rvenugopal** [comment]
@wanderingstan Please re-assign this issue.  I don't have time to work on this right now.

**Comment by wanderingstan** [comment]
No worries, @rvenugopal !

**Comment by micahalcorn** [comment]
@wanderingstan as it turns out, "alertify" could mean a few different things.

1) [The original library](https://github.com/fabien-d/alertify.js) is no longer maintained. This is the one that [is currently being used in the company-website](https://github.com/OriginProtocol/company-website/commit/1c10ad36025dcb2c4a0705945dffeb5da8879092). It is available as a [`node_module`](https://www.npmjs.com/package/alertify), but it sets [`Alertify` as a global variable](https://github.com/fabien-d/alertify.js/blob/0.3/lib/alertify.js#L18) and does not `export` anything in the ES6 style.

2) [A self-described "extreme makeover" fork](https://github.com/MohammadYounes/AlertifyJS) linked [above](https://github.com/OriginProtocol/demo-dapp/issues/46#issuecomment-356326934), which deviates quite a bit from the original API. It is available as a [`node_module`](https://www.npmjs.com/package/alertifyjs), and it can be `import`ed.

3) [A fork with an API more similar to the original](https://www.npmjs.com/package/alertify.js) but not enough to be able to use the same stylesheet in both repos (or even really the same function calls). It is available as a [node_module](https://www.npmjs.com/package/alertify.js) and can be `import`ed.

So is it beneficial for the style and UX to match the other repo? If so, do we use Webpack to import a fixed Javascript file and a global `Alertify` or do we treat it as an asset and serve it up like the old days? And whether or not the two repos need to match, does it make sense to choose a fork and move forward with it?

**Comment by ryana** [comment]
My vote is for the no longer maintained one. It's been working fine for me in several projects.

**Comment by wanderingstan** [comment]
I'm fine with using the old one too. 

Sure, we may need something fancier in the future, but no need to over-complicate until we have better sense of what we  need.

**Comment by wanderingstan** [comment]
@micahalcorn You've fixed this ages ago, right? I'm going to close it--shout if it should be re-opened.
